# Generated by carnix 0.8.11: carnix generate-nix --src ./.
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
let crates = cratesIO // rec {
  crates.cardano."0.1.0" = deps: { features?(features_.cardano."0.1.0" deps {}) }: buildRustCrate {
    crateName = "cardano";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] "cardano-deps/cardano";
    dependencies = mapFeatures features ([
      (cratesIO.crates."cbor_event"."${deps."cardano"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."cryptoxide"."${deps."cardano"."0.1.0"."cryptoxide"}" deps)
    ]
      ++ (if features.cardano."0.1.0".serde or false then [ (cratesIO.crates.serde."1.0.80" deps) ] else [])
      ++ (if features.cardano."0.1.0".serde_derive or false then [ (cratesIO.crates.serde_derive."1.0.80" deps) ] else []));
    features = mkFeatures (features."cardano"."0.1.0" or {});
  };
  features_.cardano."0.1.0" = deps: f: updateFeatures f (rec {
    cardano = fold recursiveUpdate {} [
      { "0.1.0".default = (f.cardano."0.1.0".default or true); }
      { "0.1.0".serde =
        (f.cardano."0.1.0".serde or false) ||
        (f.cardano."0.1.0".generic-serialization or false) ||
        (cardano."0.1.0"."generic-serialization" or false); }
      { "0.1.0".serde_derive =
        (f.cardano."0.1.0".serde_derive or false) ||
        (f.cardano."0.1.0".generic-serialization or false) ||
        (cardano."0.1.0"."generic-serialization" or false); }
    ];
    cbor_event."${deps.cardano."0.1.0".cbor_event}".default = true;
    cryptoxide."${deps.cardano."0.1.0".cryptoxide}".default = true;
    serde."${deps.cardano."0.1.0".serde}".default = true;
    serde_derive."${deps.cardano."0.1.0".serde_derive}".default = true;
  }) [
    (cratesIO.features_.cbor_event."${deps."cardano"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.cryptoxide."${deps."cardano"."0.1.0"."cryptoxide"}" deps)
    (cratesIO.features_.serde."${deps."cardano"."0.1.0"."serde"}" deps)
    (cratesIO.features_.serde_derive."${deps."cardano"."0.1.0"."serde_derive"}" deps)
  ];


  crates.cardano_cli."1.0.0-alpha3" = deps: { features?(features_.cardano_cli."1.0.0-alpha3" deps {}) }: buildRustCrate {
    crateName = "cardano-cli";
    version = "1.0.0-alpha3";
    authors = [ "Nicolas Di Prima <nicolas.diprima@iohk.io>" "Vincent Hanquez <vincent.hanquez@iohk.io>" ];
    src = exclude [ ".git" "target" ] ./.;
    dependencies = mapFeatures features ([
      (cratesIO.crates."base64"."${deps."cardano_cli"."1.0.0-alpha3"."base64"}" deps)
      (crates."cardano"."${deps."cardano_cli"."1.0.0-alpha3"."cardano"}" deps)
      (crates."cardano_storage"."${deps."cardano_cli"."1.0.0-alpha3"."cardano_storage"}" deps)
      (cratesIO.crates."cbor_event"."${deps."cardano_cli"."1.0.0-alpha3"."cbor_event"}" deps)
      (cratesIO.crates."clap"."${deps."cardano_cli"."1.0.0-alpha3"."clap"}" deps)
      (cratesIO.crates."console"."${deps."cardano_cli"."1.0.0-alpha3"."console"}" deps)
      (cratesIO.crates."cryptoxide"."${deps."cardano_cli"."1.0.0-alpha3"."cryptoxide"}" deps)
      (cratesIO.crates."dialoguer"."${deps."cardano_cli"."1.0.0-alpha3"."dialoguer"}" deps)
      (cratesIO.crates."dirs"."${deps."cardano_cli"."1.0.0-alpha3"."dirs"}" deps)
      (cratesIO.crates."env_logger"."${deps."cardano_cli"."1.0.0-alpha3"."env_logger"}" deps)
      (crates."exe_common"."${deps."cardano_cli"."1.0.0-alpha3"."exe_common"}" deps)
      (cratesIO.crates."humantime"."${deps."cardano_cli"."1.0.0-alpha3"."humantime"}" deps)
      (cratesIO.crates."indicatif"."${deps."cardano_cli"."1.0.0-alpha3"."indicatif"}" deps)
      (cratesIO.crates."log"."${deps."cardano_cli"."1.0.0-alpha3"."log"}" deps)
      (cratesIO.crates."rand"."${deps."cardano_cli"."1.0.0-alpha3"."rand"}" deps)
      (cratesIO.crates."serde"."${deps."cardano_cli"."1.0.0-alpha3"."serde"}" deps)
      (cratesIO.crates."serde_derive"."${deps."cardano_cli"."1.0.0-alpha3"."serde_derive"}" deps)
      (cratesIO.crates."serde_json"."${deps."cardano_cli"."1.0.0-alpha3"."serde_json"}" deps)
      (cratesIO.crates."serde_yaml"."${deps."cardano_cli"."1.0.0-alpha3"."serde_yaml"}" deps)
      (crates."storage_units"."${deps."cardano_cli"."1.0.0-alpha3"."storage_units"}" deps)
    ]);
  };
  features_.cardano_cli."1.0.0-alpha3" = deps: f: updateFeatures f (rec {
    base64."${deps.cardano_cli."1.0.0-alpha3".base64}".default = true;
    cardano = fold recursiveUpdate {} [
      { "${deps.cardano_cli."1.0.0-alpha3".cardano}"."generic-serialization" = true; }
      { "${deps.cardano_cli."1.0.0-alpha3".cardano}".default = true; }
    ];
    cardano_cli."1.0.0-alpha3".default = (f.cardano_cli."1.0.0-alpha3".default or true);
    cardano_storage."${deps.cardano_cli."1.0.0-alpha3".cardano_storage}".default = true;
    cbor_event."${deps.cardano_cli."1.0.0-alpha3".cbor_event}".default = true;
    clap = fold recursiveUpdate {} [
      { "${deps.cardano_cli."1.0.0-alpha3".clap}"."color" = true; }
      { "${deps.cardano_cli."1.0.0-alpha3".clap}"."suggestions" = true; }
      { "${deps.cardano_cli."1.0.0-alpha3".clap}"."wrap_help" = true; }
      { "${deps.cardano_cli."1.0.0-alpha3".clap}".default = (f.clap."${deps.cardano_cli."1.0.0-alpha3".clap}".default or false); }
    ];
    console."${deps.cardano_cli."1.0.0-alpha3".console}".default = true;
    cryptoxide."${deps.cardano_cli."1.0.0-alpha3".cryptoxide}".default = true;
    dialoguer."${deps.cardano_cli."1.0.0-alpha3".dialoguer}".default = true;
    dirs."${deps.cardano_cli."1.0.0-alpha3".dirs}".default = true;
    env_logger."${deps.cardano_cli."1.0.0-alpha3".env_logger}".default = true;
    exe_common."${deps.cardano_cli."1.0.0-alpha3".exe_common}".default = true;
    humantime."${deps.cardano_cli."1.0.0-alpha3".humantime}".default = true;
    indicatif."${deps.cardano_cli."1.0.0-alpha3".indicatif}".default = true;
    log."${deps.cardano_cli."1.0.0-alpha3".log}".default = true;
    rand."${deps.cardano_cli."1.0.0-alpha3".rand}".default = true;
    serde."${deps.cardano_cli."1.0.0-alpha3".serde}".default = true;
    serde_derive."${deps.cardano_cli."1.0.0-alpha3".serde_derive}".default = true;
    serde_json."${deps.cardano_cli."1.0.0-alpha3".serde_json}".default = true;
    serde_yaml."${deps.cardano_cli."1.0.0-alpha3".serde_yaml}".default = true;
    storage_units."${deps.cardano_cli."1.0.0-alpha3".storage_units}".default = true;
  }) [
    (cratesIO.features_.base64."${deps."cardano_cli"."1.0.0-alpha3"."base64"}" deps)
    (features_.cardano."${deps."cardano_cli"."1.0.0-alpha3"."cardano"}" deps)
    (features_.cardano_storage."${deps."cardano_cli"."1.0.0-alpha3"."cardano_storage"}" deps)
    (cratesIO.features_.cbor_event."${deps."cardano_cli"."1.0.0-alpha3"."cbor_event"}" deps)
    (cratesIO.features_.clap."${deps."cardano_cli"."1.0.0-alpha3"."clap"}" deps)
    (cratesIO.features_.console."${deps."cardano_cli"."1.0.0-alpha3"."console"}" deps)
    (cratesIO.features_.cryptoxide."${deps."cardano_cli"."1.0.0-alpha3"."cryptoxide"}" deps)
    (cratesIO.features_.dialoguer."${deps."cardano_cli"."1.0.0-alpha3"."dialoguer"}" deps)
    (cratesIO.features_.dirs."${deps."cardano_cli"."1.0.0-alpha3"."dirs"}" deps)
    (cratesIO.features_.env_logger."${deps."cardano_cli"."1.0.0-alpha3"."env_logger"}" deps)
    (features_.exe_common."${deps."cardano_cli"."1.0.0-alpha3"."exe_common"}" deps)
    (cratesIO.features_.humantime."${deps."cardano_cli"."1.0.0-alpha3"."humantime"}" deps)
    (cratesIO.features_.indicatif."${deps."cardano_cli"."1.0.0-alpha3"."indicatif"}" deps)
    (cratesIO.features_.log."${deps."cardano_cli"."1.0.0-alpha3"."log"}" deps)
    (cratesIO.features_.rand."${deps."cardano_cli"."1.0.0-alpha3"."rand"}" deps)
    (cratesIO.features_.serde."${deps."cardano_cli"."1.0.0-alpha3"."serde"}" deps)
    (cratesIO.features_.serde_derive."${deps."cardano_cli"."1.0.0-alpha3"."serde_derive"}" deps)
    (cratesIO.features_.serde_json."${deps."cardano_cli"."1.0.0-alpha3"."serde_json"}" deps)
    (cratesIO.features_.serde_yaml."${deps."cardano_cli"."1.0.0-alpha3"."serde_yaml"}" deps)
    (features_.storage_units."${deps."cardano_cli"."1.0.0-alpha3"."storage_units"}" deps)
  ];


  crates.cardano_storage."0.1.0" = deps: { features?(features_.cardano_storage."0.1.0" deps {}) }: buildRustCrate {
    crateName = "cardano-storage";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] "cardano-deps/storage";
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."cardano_storage"."0.1.0"."cardano"}" deps)
      (cratesIO.crates."cbor_event"."${deps."cardano_storage"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."log"."${deps."cardano_storage"."0.1.0"."log"}" deps)
      (cratesIO.crates."rand"."${deps."cardano_storage"."0.1.0"."rand"}" deps)
      (crates."storage_units"."${deps."cardano_storage"."0.1.0"."storage_units"}" deps)
    ]);
  };
  features_.cardano_storage."0.1.0" = deps: f: updateFeatures f (rec {
    cardano."${deps.cardano_storage."0.1.0".cardano}".default = true;
    cardano_storage."0.1.0".default = (f.cardano_storage."0.1.0".default or true);
    cbor_event."${deps.cardano_storage."0.1.0".cbor_event}".default = true;
    log."${deps.cardano_storage."0.1.0".log}".default = true;
    rand."${deps.cardano_storage."0.1.0".rand}".default = true;
    storage_units."${deps.cardano_storage."0.1.0".storage_units}".default = true;
  }) [
    (features_.cardano."${deps."cardano_storage"."0.1.0"."cardano"}" deps)
    (cratesIO.features_.cbor_event."${deps."cardano_storage"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.log."${deps."cardano_storage"."0.1.0"."log"}" deps)
    (cratesIO.features_.rand."${deps."cardano_storage"."0.1.0"."rand"}" deps)
    (features_.storage_units."${deps."cardano_storage"."0.1.0"."storage_units"}" deps)
  ];


  crates.exe_common."0.1.0" = deps: { features?(features_.exe_common."0.1.0" deps {}) }: buildRustCrate {
    crateName = "exe-common";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] "cardano-deps/exe-common";
    dependencies = mapFeatures features ([
      (cratesIO.crates."base64"."${deps."exe_common"."0.1.0"."base64"}" deps)
      (crates."cardano"."${deps."exe_common"."0.1.0"."cardano"}" deps)
      (crates."cardano_storage"."${deps."exe_common"."0.1.0"."cardano_storage"}" deps)
      (cratesIO.crates."cbor_event"."${deps."exe_common"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."futures"."${deps."exe_common"."0.1.0"."futures"}" deps)
      (cratesIO.crates."hyper"."${deps."exe_common"."0.1.0"."hyper"}" deps)
      (cratesIO.crates."log"."${deps."exe_common"."0.1.0"."log"}" deps)
      (crates."protocol"."${deps."exe_common"."0.1.0"."protocol"}" deps)
      (cratesIO.crates."rand"."${deps."exe_common"."0.1.0"."rand"}" deps)
      (cratesIO.crates."serde"."${deps."exe_common"."0.1.0"."serde"}" deps)
      (cratesIO.crates."serde_derive"."${deps."exe_common"."0.1.0"."serde_derive"}" deps)
      (cratesIO.crates."serde_json"."${deps."exe_common"."0.1.0"."serde_json"}" deps)
      (cratesIO.crates."serde_yaml"."${deps."exe_common"."0.1.0"."serde_yaml"}" deps)
      (crates."storage_units"."${deps."exe_common"."0.1.0"."storage_units"}" deps)
      (cratesIO.crates."tokio_core"."${deps."exe_common"."0.1.0"."tokio_core"}" deps)
    ]);
  };
  features_.exe_common."0.1.0" = deps: f: updateFeatures f (rec {
    base64."${deps.exe_common."0.1.0".base64}".default = true;
    cardano = fold recursiveUpdate {} [
      { "${deps.exe_common."0.1.0".cardano}"."generic-serialization" = true; }
      { "${deps.exe_common."0.1.0".cardano}".default = true; }
    ];
    cardano_storage."${deps.exe_common."0.1.0".cardano_storage}".default = true;
    cbor_event."${deps.exe_common."0.1.0".cbor_event}".default = true;
    exe_common."0.1.0".default = (f.exe_common."0.1.0".default or true);
    futures."${deps.exe_common."0.1.0".futures}".default = true;
    hyper."${deps.exe_common."0.1.0".hyper}".default = true;
    log."${deps.exe_common."0.1.0".log}".default = true;
    protocol."${deps.exe_common."0.1.0".protocol}".default = true;
    rand."${deps.exe_common."0.1.0".rand}".default = true;
    serde."${deps.exe_common."0.1.0".serde}".default = true;
    serde_derive."${deps.exe_common."0.1.0".serde_derive}".default = true;
    serde_json."${deps.exe_common."0.1.0".serde_json}".default = true;
    serde_yaml."${deps.exe_common."0.1.0".serde_yaml}".default = true;
    storage_units."${deps.exe_common."0.1.0".storage_units}".default = true;
    tokio_core."${deps.exe_common."0.1.0".tokio_core}".default = true;
  }) [
    (cratesIO.features_.base64."${deps."exe_common"."0.1.0"."base64"}" deps)
    (features_.cardano."${deps."exe_common"."0.1.0"."cardano"}" deps)
    (features_.cardano_storage."${deps."exe_common"."0.1.0"."cardano_storage"}" deps)
    (cratesIO.features_.cbor_event."${deps."exe_common"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.futures."${deps."exe_common"."0.1.0"."futures"}" deps)
    (cratesIO.features_.hyper."${deps."exe_common"."0.1.0"."hyper"}" deps)
    (cratesIO.features_.log."${deps."exe_common"."0.1.0"."log"}" deps)
    (features_.protocol."${deps."exe_common"."0.1.0"."protocol"}" deps)
    (cratesIO.features_.rand."${deps."exe_common"."0.1.0"."rand"}" deps)
    (cratesIO.features_.serde."${deps."exe_common"."0.1.0"."serde"}" deps)
    (cratesIO.features_.serde_derive."${deps."exe_common"."0.1.0"."serde_derive"}" deps)
    (cratesIO.features_.serde_json."${deps."exe_common"."0.1.0"."serde_json"}" deps)
    (cratesIO.features_.serde_yaml."${deps."exe_common"."0.1.0"."serde_yaml"}" deps)
    (features_.storage_units."${deps."exe_common"."0.1.0"."storage_units"}" deps)
    (cratesIO.features_.tokio_core."${deps."exe_common"."0.1.0"."tokio_core"}" deps)
  ];


  crates.protocol."0.1.0" = deps: { features?(features_.protocol."0.1.0" deps {}) }: buildRustCrate {
    crateName = "protocol";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] "cardano-deps/exe-common/../protocol";
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."protocol"."0.1.0"."cardano"}" deps)
      (cratesIO.crates."cbor_event"."${deps."protocol"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."log"."${deps."protocol"."0.1.0"."log"}" deps)
    ]);
  };
  features_.protocol."0.1.0" = deps: f: updateFeatures f (rec {
    cardano."${deps.protocol."0.1.0".cardano}".default = true;
    cbor_event."${deps.protocol."0.1.0".cbor_event}".default = true;
    log."${deps.protocol."0.1.0".log}".default = true;
    protocol."0.1.0".default = (f.protocol."0.1.0".default or true);
  }) [
    (features_.cardano."${deps."protocol"."0.1.0"."cardano"}" deps)
    (cratesIO.features_.cbor_event."${deps."protocol"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.log."${deps."protocol"."0.1.0"."log"}" deps)
  ];


  crates.storage_units."0.1.0" = deps: { features?(features_.storage_units."0.1.0" deps {}) }: buildRustCrate {
    crateName = "storage-units";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] "cardano-deps/exe-common/../storage-units";
    dependencies = mapFeatures features ([
      (cratesIO.crates."cryptoxide"."${deps."storage_units"."0.1.0"."cryptoxide"}" deps)
      (cratesIO.crates."rand"."${deps."storage_units"."0.1.0"."rand"}" deps)
    ]);
  };
  features_.storage_units."0.1.0" = deps: f: updateFeatures f (rec {
    cryptoxide."${deps.storage_units."0.1.0".cryptoxide}".default = true;
    rand."${deps.storage_units."0.1.0".rand}".default = true;
    storage_units."0.1.0".default = (f.storage_units."0.1.0".default or true);
  }) [
    (cratesIO.features_.cryptoxide."${deps."storage_units"."0.1.0"."cryptoxide"}" deps)
    (cratesIO.features_.rand."${deps."storage_units"."0.1.0"."rand"}" deps)
  ];



}; in

rec {
  cardano_cli = crates.crates.cardano_cli."1.0.0-alpha3" deps;
  __all = [ (cardano_cli {}) ];
  deps.aho_corasick."0.6.9" = {
    memchr = "2.1.1";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.6";
  };
  deps.argon2rs."0.2.5" = {
    blake2_rfc = "0.2.18";
    scoped_threadpool = "0.1.9";
  };
  deps.arrayvec."0.4.8" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.1";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.backtrace."0.3.9" = {
    cfg_if = "0.1.6";
    rustc_demangle = "0.1.9";
    backtrace_sys = "0.1.24";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.backtrace_sys."0.1.24" = {
    libc = "0.2.44";
    cc = "1.0.25";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.2.7";
    safemem = "0.3.0";
  };
  deps.bitflags."1.0.4" = {};
  deps.blake2_rfc."0.2.18" = {
    arrayvec = "0.4.8";
    constant_time_eq = "0.1.3";
  };
  deps.byteorder."1.2.7" = {};
  deps.bytes."0.4.11" = {
    byteorder = "1.2.7";
    iovec = "0.1.2";
  };
  deps.cardano."0.1.0" = {
    cbor_event = "1.0.1";
    cryptoxide = "0.1.0";
    serde = "1.0.80";
    serde_derive = "1.0.80";
  };
  deps.cardano_cli."1.0.0-alpha3" = {
    base64 = "0.9.3-";
    cardano = "0.1.0-";
    cardano_storage = "0.1.0-";
    cbor_event = "1.0.1-";
    clap = "2.32.0-";
    console = "0.7.1-";
    cryptoxide = "0.1.0-";
    dialoguer = "0.3.0-";
    dirs = "1.0.4-";
    env_logger = "0.5.13-";
    exe_common = "0.1.0-";
    humantime = "1.2.0-";
    indicatif = "0.9.0-";
    log = "0.4.6-";
    rand = "0.5.5-";
    serde = "1.0.80-";
    serde_derive = "1.0.80-";
    serde_json = "1.0.33-";
    serde_yaml = "0.8.8-";
    storage_units = "0.1.0-";
  };
  deps.cardano_storage."0.1.0" = {
    cardano = "0.1.0";
    cbor_event = "1.0.1";
    log = "0.4.6";
    rand = "0.5.5";
    storage_units = "0.1.0";
  };
  deps.cbor_event."1.0.1" = {};
  deps.cc."1.0.25" = {};
  deps.cfg_if."0.1.6" = {};
  deps.clap."2.32.0" = {
    atty = "0.2.11";
    bitflags = "1.0.4";
    strsim = "0.7.0";
    term_size = "0.3.1";
    textwrap = "0.10.0";
    unicode_width = "0.1.5";
    ansi_term = "0.11.0";
  };
  deps.clicolors_control."0.3.1" = {
    lazy_static = "1.2.0";
    libc = "0.2.44";
    atty = "0.2.11";
    winapi = "0.3.6";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.4";
  };
  deps.console."0.7.1" = {
    atty = "0.2.11";
    clicolors_control = "0.3.1";
    lazy_static = "1.2.0";
    libc = "0.2.44";
    parking_lot = "0.7.0";
    regex = "1.1.0";
    unicode_width = "0.1.5";
    termios = "0.3.1";
    winapi = "0.3.6";
  };
  deps.constant_time_eq."0.1.3" = {};
  deps.crossbeam_deque."0.6.2" = {
    crossbeam_epoch = "0.6.1";
    crossbeam_utils = "0.6.1";
  };
  deps.crossbeam_epoch."0.6.1" = {
    arrayvec = "0.4.8";
    cfg_if = "0.1.6";
    crossbeam_utils = "0.6.1";
    lazy_static = "1.2.0";
    memoffset = "0.2.1";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_utils."0.6.1" = {
    cfg_if = "0.1.6";
  };
  deps.cryptoxide."0.1.0" = {};
  deps.dialoguer."0.3.0" = {
    console = "0.7.1";
    lazy_static = "1.2.0";
    tempfile = "2.2.0";
  };
  deps.dirs."1.0.4" = {
    redox_users = "0.2.0";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.dtoa."0.4.3" = {};
  deps.env_logger."0.5.13" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.1.0";
    termcolor = "1.0.4";
  };
  deps.exe_common."0.1.0" = {
    base64 = "0.9.3";
    cardano = "0.1.0";
    cardano_storage = "0.1.0";
    cbor_event = "1.0.1";
    futures = "0.1.25";
    hyper = "0.11.27";
    log = "0.4.6";
    protocol = "0.1.0";
    rand = "0.5.5";
    serde = "1.0.80";
    serde_derive = "1.0.80";
    serde_json = "1.0.33";
    serde_yaml = "0.7.5";
    storage_units = "0.1.0";
    tokio_core = "0.1.17";
  };
  deps.failure."0.1.3" = {
    backtrace = "0.3.9";
    failure_derive = "0.1.3";
  };
  deps.failure_derive."0.1.3" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    syn = "0.15.22";
    synstructure = "0.10.1";
  };
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.4";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.futures."0.1.25" = {};
  deps.futures_cpupool."0.1.8" = {
    futures = "0.1.25";
    num_cpus = "1.8.0";
  };
  deps.httparse."1.3.3" = {};
  deps.humantime."1.2.0" = {
    quick_error = "1.2.2";
  };
  deps.hyper."0.11.27" = {
    base64 = "0.9.3";
    bytes = "0.4.11";
    futures = "0.1.25";
    futures_cpupool = "0.1.8";
    httparse = "1.3.3";
    iovec = "0.1.2";
    language_tags = "0.2.2";
    log = "0.4.6";
    mime = "0.3.12";
    net2 = "0.2.33";
    percent_encoding = "1.0.1";
    relay = "0.1.1";
    time = "0.1.40";
    tokio_core = "0.1.17";
    tokio_io = "0.1.10";
    tokio_proto = "0.1.1";
    tokio_service = "0.1.0";
    unicase = "2.2.0";
    want = "0.0.4";
  };
  deps.indicatif."0.9.0" = {
    console = "0.7.1";
    lazy_static = "0.2.11";
    parking_lot = "0.7.0";
    regex = "0.2.11";
  };
  deps.iovec."0.1.2" = {
    libc = "0.2.44";
    winapi = "0.2.8";
  };
  deps.itoa."0.4.3" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.language_tags."0.2.2" = {};
  deps.lazy_static."0.2.11" = {};
  deps.lazy_static."1.2.0" = {};
  deps.lazycell."1.2.1" = {};
  deps.libc."0.2.44" = {};
  deps.linked_hash_map."0.5.1" = {};
  deps.lock_api."0.1.5" = {
    owning_ref = "0.4.0";
    scopeguard = "0.3.3";
  };
  deps.log."0.3.9" = {
    log = "0.4.6";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.6";
  };
  deps.memchr."2.1.1" = {
    cfg_if = "0.1.6";
    libc = "0.2.44";
    version_check = "0.1.5";
  };
  deps.memoffset."0.2.1" = {};
  deps.mime."0.3.12" = {
    unicase = "2.2.0";
  };
  deps.mio."0.6.16" = {
    iovec = "0.1.2";
    lazycell = "1.2.1";
    log = "0.4.6";
    net2 = "0.2.33";
    slab = "0.4.1";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.44";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_uds."0.6.7" = {
    iovec = "0.1.2";
    libc = "0.2.44";
    mio = "0.6.16";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.6";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.nodrop."0.1.13" = {};
  deps.num_cpus."1.8.0" = {
    libc = "0.2.44";
  };
  deps.owning_ref."0.4.0" = {
    stable_deref_trait = "1.1.1";
  };
  deps.parking_lot."0.6.4" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.3.1";
  };
  deps.parking_lot."0.7.0" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.4.0";
  };
  deps.parking_lot_core."0.3.1" = {
    rand = "0.5.5";
    smallvec = "0.6.7";
    rustc_version = "0.2.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.parking_lot_core."0.4.0" = {
    rand = "0.6.1";
    smallvec = "0.6.7";
    rustc_version = "0.2.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.proc_macro2."0.4.24" = {
    unicode_xid = "0.1.0";
  };
  deps.protocol."0.1.0" = {
    cardano = "0.1.0";
    cbor_event = "1.0.1";
    log = "0.4.6";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.6.10" = {
    proc_macro2 = "0.4.24";
  };
  deps.rand."0.3.22" = {
    libc = "0.2.44";
    rand = "0.4.3";
    fuchsia_zircon = "0.3.3";
  };
  deps.rand."0.4.3" = {
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand."0.5.5" = {
    rand_core = "0.2.2";
    cloudabi = "0.0.3";
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand."0.6.1" = {
    rand_chacha = "0.1.0";
    rand_core = "0.3.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_pcg = "0.1.1";
    rand_xorshift = "0.1.0";
    rustc_version = "0.2.3";
    cloudabi = "0.0.3";
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand_chacha."0.1.0" = {
    rand_core = "0.3.0";
    rustc_version = "0.2.3";
  };
  deps.rand_core."0.2.2" = {
    rand_core = "0.3.0";
  };
  deps.rand_core."0.3.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.0";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.0";
  };
  deps.rand_pcg."0.1.1" = {
    rand_core = "0.3.0";
    rustc_version = "0.2.3";
  };
  deps.rand_xorshift."0.1.0" = {
    rand_core = "0.3.0";
  };
  deps.redox_syscall."0.1.43" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.43";
  };
  deps.redox_users."0.2.0" = {
    argon2rs = "0.2.5";
    failure = "0.1.3";
    rand = "0.4.3";
    redox_syscall = "0.1.43";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.9";
    memchr = "2.1.1";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex."1.1.0" = {
    aho_corasick = "0.6.9";
    memchr = "2.1.1";
    regex_syntax = "0.6.4";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.3";
  };
  deps.regex_syntax."0.6.4" = {
    ucd_util = "0.1.3";
  };
  deps.relay."0.1.1" = {
    futures = "0.1.25";
  };
  deps.rustc_demangle."0.1.9" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."0.2.7" = {};
  deps.safemem."0.3.0" = {};
  deps.scoped_tls."0.1.2" = {};
  deps.scoped_threadpool."0.1.9" = {};
  deps.scopeguard."0.3.3" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.80" = {};
  deps.serde_derive."1.0.80" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    syn = "0.15.22";
  };
  deps.serde_json."1.0.33" = {
    itoa = "0.4.3";
    ryu = "0.2.7";
    serde = "1.0.80";
  };
  deps.serde_yaml."0.7.5" = {
    dtoa = "0.4.3";
    linked_hash_map = "0.5.1";
    serde = "1.0.80";
    yaml_rust = "0.4.2";
  };
  deps.serde_yaml."0.8.8" = {
    dtoa = "0.4.3";
    linked_hash_map = "0.5.1";
    serde = "1.0.80";
    yaml_rust = "0.4.2";
  };
  deps.slab."0.3.0" = {};
  deps.slab."0.4.1" = {};
  deps.smallvec."0.2.1" = {};
  deps.smallvec."0.6.7" = {
    unreachable = "1.0.0";
  };
  deps.stable_deref_trait."1.1.1" = {};
  deps.storage_units."0.1.0" = {
    cryptoxide = "0.1.0";
    rand = "0.5.5";
  };
  deps.strsim."0.7.0" = {};
  deps.syn."0.15.22" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.1" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    syn = "0.15.22";
    unicode_xid = "0.1.0";
  };
  deps.take."0.1.0" = {};
  deps.tempfile."2.2.0" = {
    rand = "0.3.22";
    redox_syscall = "0.1.43";
    libc = "0.2.44";
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
  };
  deps.term_size."0.3.1" = {
    libc = "0.2.44";
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
  };
  deps.termcolor."1.0.4" = {
    wincolor = "1.0.1";
  };
  deps.termion."1.5.1" = {
    libc = "0.2.44";
    redox_syscall = "0.1.43";
    redox_termios = "0.1.1";
  };
  deps.termios."0.3.1" = {
    libc = "0.2.44";
  };
  deps.textwrap."0.10.0" = {
    term_size = "0.3.1";
    unicode_width = "0.1.5";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.2.0";
  };
  deps.time."0.1.40" = {
    libc = "0.2.44";
    redox_syscall = "0.1.43";
    winapi = "0.3.6";
  };
  deps.tokio."0.1.13" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    mio = "0.6.16";
    num_cpus = "1.8.0";
    tokio_codec = "0.1.1";
    tokio_current_thread = "0.1.4";
    tokio_executor = "0.1.5";
    tokio_fs = "0.1.4";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
    tokio_tcp = "0.1.2";
    tokio_threadpool = "0.1.9";
    tokio_timer = "0.2.8";
    tokio_udp = "0.1.3";
    tokio_uds = "0.2.4";
  };
  deps.tokio_codec."0.1.1" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    tokio_io = "0.1.10";
  };
  deps.tokio_core."0.1.17" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    log = "0.4.6";
    mio = "0.6.16";
    scoped_tls = "0.1.2";
    tokio = "0.1.13";
    tokio_executor = "0.1.5";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
    tokio_timer = "0.2.8";
  };
  deps.tokio_current_thread."0.1.4" = {
    futures = "0.1.25";
    tokio_executor = "0.1.5";
  };
  deps.tokio_executor."0.1.5" = {
    futures = "0.1.25";
  };
  deps.tokio_fs."0.1.4" = {
    futures = "0.1.25";
    tokio_io = "0.1.10";
    tokio_threadpool = "0.1.9";
  };
  deps.tokio_io."0.1.10" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    log = "0.4.6";
  };
  deps.tokio_proto."0.1.1" = {
    futures = "0.1.25";
    log = "0.3.9";
    net2 = "0.2.33";
    rand = "0.3.22";
    slab = "0.3.0";
    smallvec = "0.2.1";
    take = "0.1.0";
    tokio_core = "0.1.17";
    tokio_io = "0.1.10";
    tokio_service = "0.1.0";
  };
  deps.tokio_reactor."0.1.7" = {
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    lazy_static = "1.2.0";
    log = "0.4.6";
    mio = "0.6.16";
    num_cpus = "1.8.0";
    parking_lot = "0.6.4";
    slab = "0.4.1";
    tokio_executor = "0.1.5";
    tokio_io = "0.1.10";
  };
  deps.tokio_service."0.1.0" = {
    futures = "0.1.25";
  };
  deps.tokio_tcp."0.1.2" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    mio = "0.6.16";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.tokio_threadpool."0.1.9" = {
    crossbeam_deque = "0.6.2";
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    log = "0.4.6";
    num_cpus = "1.8.0";
    rand = "0.6.1";
    tokio_executor = "0.1.5";
  };
  deps.tokio_timer."0.2.8" = {
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    slab = "0.4.1";
    tokio_executor = "0.1.5";
  };
  deps.tokio_udp."0.1.3" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    log = "0.4.6";
    mio = "0.6.16";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.tokio_uds."0.2.4" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    libc = "0.2.44";
    log = "0.4.6";
    mio = "0.6.16";
    mio_uds = "0.6.7";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.try_lock."0.1.0" = {};
  deps.ucd_util."0.1.3" = {};
  deps.unicase."2.2.0" = {
    version_check = "0.1.5";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.unreachable."1.0.0" = {
    void = "1.0.2";
  };
  deps.utf8_ranges."1.0.2" = {};
  deps.version_check."0.1.5" = {};
  deps.void."1.0.2" = {};
  deps.want."0.0.4" = {
    futures = "0.1.25";
    log = "0.4.6";
    try_lock = "0.1.0";
  };
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.6" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.1" = {
    winapi = "0.3.6";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.wincolor."1.0.1" = {
    winapi = "0.3.6";
    winapi_util = "0.1.1";
  };
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.yaml_rust."0.4.2" = {
    linked_hash_map = "0.5.1";
  };
}
